replicaCount: 1
cpu:
  request: "0.1"
  limit: "1"
memory:
  request: 20Mi
  limit: 40Mi
redis:
  master:
    podAnnotations:
      linkerd.io/inject: enabled
    persistence:
      enabled: false
      size: 1Gi
  architecture: standalone
  fullnameOverride: cheetah-accounts-redis
  auth:
    existingSecret: cheetah-accounts-redis-password
    existingSecretPasswordKey: password
  cluster:
    enabled: false
  volumePermissions:
    enabled: true
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001