kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      additionalScrapeConfigsSecret:
        enabled: true
        name: prometheus-additional-scrape-configs
        key: additional.yaml
      podMonitorSelector:
        matchLabels:
          monitor: cheetah
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: monitoring/prometheus-web-auth-secret
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      ingressClassName: nginx
      pathType: ImplementationSpecific
      enabled: true
  grafana:
    adminUser: admin
    replicas: 1
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      ingressClassName: nginx
      pathType: ImplementationSpecific
      enabled: true
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://monitoring-loki:3100
    sidecar:
      dashboards:
        enabled: true
  alertmanager:
    enabled: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: monitoring/prometheus-web-auth-secret
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      ingressClassName: nginx
      pathType: ImplementationSpecific
      enabled: true
