kube-prometheus-stack:
  kube-state-metrics:
    tolerations:
      - key: "type"
        value: "monitoring"
        operator: "Equal"
        effect: "NoSchedule"
    nodeSelector:
      type: "monitoring"
  prometheusOperator:
    admissionWebhooks:
      patch:
        tolerations:
          - key: "type"
            value: "monitoring"
            operator: "Equal"
            effect: "NoSchedule"
        nodeSelector:
          type: "monitoring"
    tolerations:
      - key: "type"
        value: "monitoring"
        operator: "Equal"
        effect: "NoSchedule"
    nodeSelector:
      type: "monitoring"
  prometheus:
    prometheusSpec:
      tolerations:
        - key: "type"
          value: "monitoring"
          operator: "Equal"
          effect: "NoSchedule"
      nodeSelector:
        type: "monitoring"
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 50Gi
  grafana:
    tolerations:
      - key: "type"
        value: "monitoring"
        operator: "Equal"
        effect: "NoSchedule"
    nodeSelector:
      type: "monitoring"
    persistence:
      enabled: true
      accessModes: [ "ReadWriteOnce" ]
      size: 10Gi
  alertmanager:
    alertmanagerSpec:
      tolerations:
        - key: "type"
          value: "monitoring"
          operator: "Equal"
          effect: "NoSchedule"
      nodeSelector:
        type: "monitoring"
loki:
  tolerations:
    - key: "type"
      value: "monitoring"
      operator: "Equal"
      effect: "NoSchedule"
  nodeSelector:
    type: "monitoring"
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 100Gi

