kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 20Gi
  grafana:
    persistence:
      enabled: true
      accessModes: [ "ReadWriteOnce" ]
      size: 5Gi
loki:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi

