kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: do-block-storage
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 5Gi
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: monitoring/prometheus-web-auth-secret
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      ingressClassName: nginx
      pathType: ImplementationSpecific
      enabled: true
  grafana:
    adminUser: admin
    persistence:
      enabled: true
      storageClassName: do-block-storage
      accessModes: [ "ReadWriteOnce" ]
      size: 5Gi
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      ingressClassName: nginx
      pathType: ImplementationSpecific
      enabled: true

