# пример конфигурации шаблонов комнат для фабрики
# в реальном проекте должна использоваться другая config-map
apiVersion: v1
kind: ConfigMap
metadata:
  name: "rooms-template-example"
data:
  groups.yaml: |
   groups:
    test_group: 4444
  prefab.yaml: |
    prefab:
      template: 1234
      access:
        test_group: deny
      fields:
        - name: a
          id: 1
          type: struct
          value:
            uid: arts80
            rank: 100
          access:
            test_group: deny
        - name: b
          id: 2
          type: i64
          value: 4
          access:
            test_group: deny
        - name: c
          id: 3
          type: f64
  gubaha.yaml: |
    room:
      groups: /groups
      objects:
        - prefab: /prefab
          group: test_group
        - prefab: /prefab
          group: test_group
          fields:
            - name: a
              type: i64
              value: 12345
          extend:
            - id: 4321
              type: i64
              value: 12345