# пример конфигурации шаблонов комнат для фабрики
# в реальном проекте должна использоваться другая config-map
apiVersion: v1
kind: ConfigMap
metadata:
  name: "rooms-template-example"
data:
  gubaha.yaml: |
    objects:
    - id: 555
      template: 1
      groups: 4857
      fields:
        longs:
          10: 100100
        floats:
          5: 3.14
          10: 2.68
        structures:
          5:
            uid: arts80
            rank: 100
          10:
            - 15
            - 26
    permissions:
      templates:
        - template: 1
          rules:
            - groups: 12495
              permission: deny
          fields:
            - id: 100
              type: long
              rules:
                - groups: 5677
                  permission: ro