[package]
name = "cheetah-auth-authentication"
version = "999.999.999"
edition = "2018"

[[bin]]
name = "service"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
tonic = "0.5.0"
prost = "0.8.0"
tokio = { version = "1.7", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tokio-stream = { version = "0.1.7", features = ["net"] }
tower = { version = "0.4" }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres", "migrate", "ipnetwork", "chrono"] }
async-trait = "0.1.50"
log = "0.4"
pretty_env_logger = "0.4.0"
ipnetwork = "0.18.0"
rand = "0.8"
cheetah-microservice = { path = "../../../Microservice" }
jsonwebtoken-google = { version = "0.1.1" }

# обход проблемы https://github.com/Alexhuszagh/rust-lexical/issues/65
# это зависимость sqlx, как только они включат новую зависимость lexical-core
# то эту строчку надо удалить
lexical-core = "0.7.6"

[dev-dependencies]
testcontainers = "0.12.0"
lazy_static = "1.4.0"
cheetah-auth-cerberus = { path = "../../Cerberus/Service", features = ["test-helper"] }
jsonwebtoken-google = { version = "0.1.1", features = ["test-helper"] }

[build-dependencies]
tonic-build = "0.5.1"