version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/components/auth/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/components/relay/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/components/cerberus/"
    schedule:
     interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
     interval: "daily"