version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/server/authentication/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/server/relay/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/server/cerberus/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"