theme:
  name: material
  custom_dir: overrides
  language: ru
  features:
    - navigation.instant
    - navigation.sections
  palette:
    primary: blue grey
site_name: Cheetah Game Platform
docs_dir: content
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
plugins:
  - search:
      lang: ru
extra:
  disqus: remark42
nav:
  - "Введение": "index.md"
  - "Unity":
      - "Установка платформы": "unity/setup.md"
      - "Запуск локального сервера": "unity/local-server.md"
  - "Компоненты":
      - "Аутентификация":
          - "Введение": "components/authentication/index.md"
          - "Временная регистрация": "components/authentication/cookie.md"
          - "Google": "components/authentication/google.md"
      - "Выбор битвы": "components/matchmaking/index.md"
      - "Битва реального времени":
          - "Введение": "components/relay/index.md"
          - "Базовые понятия":
              - "Клиент": "components/relay/basics/client.md"
              - "Комната": "components/relay/basics/room.md"
              - "Объект": "components/relay/basics/object.md"
              - "Канал": "components/relay/basics/channel.md"
          - "Команды":
              - "События": "components/relay/commands/event.md"
              - "Структуры": "components/relay/commands/structure.md"
              - "Целые числа": "components/relay/commands/long.md"
              - "Вещественные числа": "components/relay/commands/double.md"
              - "Сериализация": "components/relay/commands/serialization.md"
              - "Удаление поля": "components/relay/commands/delete_field.md"
              - "CompareAndSet": "components/relay/commands/compare_and_set.md"
          - "Конфигурация": "components/relay/configuration.md"
          - "Локальная разработка":
              - "Эмуляция параметров сети": "components/relay/develop/network.md"
              - "Логирование": "components/relay/develop/logger.md"
              - "Панель сетевых команд": "components/relay/develop/commands-panel.md"
              - "Просмотр состояния сервера": "components/relay/develop/dump-panel.md"
      - "Статистика": "components/statistics/index.md"
      - "Совместимость клиента и сервера": "components/system/compatibility.md"