[package]
name = "cheetah-matches-relay"
version = "0.1.0"
authors = ["kviring <alex@kviring.com>"]
edition = "2018"

[[bin]]
name = "service"
path = "src/bin/service.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
rand = "0.8.4"
log = "0.4"
stderrlog = "0.5.0"
indexmap = { version = "1.7.0", features = ["serde-1"] }
cheetah-matches-relay-common = { path = "../Common/" }
fnv = "1.0.7"
serde = { version = "1.0.127", features = ["derive", "rc"] }
heapless = { version = "0.7.3", features = ["serde"] }
futures = "0.3.16"
rmpv = { version = "0.4.7", features = ["with-serde"] }
serde_json = "1.0.69"
rmp-serde = "0.15.5"
serde_yaml = "0.8.17"
tokio = { version = "1.10", features = ["rt-multi-thread", "time", "fs", "macros", "net", "sync"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
tonic = "0.6.1"
prost = "0.9.0"
rymder = "0.2.2"
strum_macros = "0.22.0"
cheetah-microservice = { path = "../../../Microservice" }

[build-dependencies]
tonic-build = {version="0.6.0", features=["rustfmt"]}