[package]
name = "cheetah-matches-relay"
version = "0.1.0"
authors = ["kviring <alex@kviring.com>"]
edition = "2018"

[[bin]]
name = "service"
path = "src/bin/service.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
rand = "0.8.4"
indexmap = { version = "1.8.0" }
cheetah-matches-relay-common = { path = "../Common/" }
fnv = "1.0.7"
serde = { version = "1.0.132", features = ["derive", "rc"] }
heapless = { version = "0.7.10", features = ["serde"] }
futures = "0.3.21"
serde_json = "1.0.73"
tokio = { version = "1.16.1", features = ["rt-multi-thread", "time", "fs", "macros", "net", "sync"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
tonic = "0.6.2"
prost = "0.9.0"
rymder = "0.3.0"
strum_macros = "0.23.1"
cheetah-microservice = { path = "../../../Microservice" }
tonic-web = "0.2.0"
thiserror = "1.0.30"
tracing = "0.1.30"


[build-dependencies]
tonic-build = {version="0.6.2", features=["rustfmt"]}
