[workspace]
members = [
    "libraries/Microservice",
    "Accounts/server",
    "UserStore/server",
    "matches/Factory/server",
    "matches/Registry/server",
    "matches/StubMatchmaking/server",
    "matches/StubRegistry/server",
    "matches/Relay/server/Macro/",
    "matches/Relay/server/Common/",
    "matches/Relay/server/Client",
    "matches/Relay/server/Server",
    "statistics/Events/server/",
    "system/Compatibility/server/",
]
