[package]
name = "cheetah-microservice"
version = "999.999.999"
edition = "2018"

[features]
default = ["tonic"]
auth = ["tonic", "prost"]
matches = ["tonic", "prost"]
postgresql_test_helper = ["testcontainers", "sqlx"]

[dependencies]
log = "0.4"
pretty_env_logger = "0.4.0"
jsonwebtoken = "7.2.0"
serde = { version = "1.0", features = ["derive"] }

# опциональные зависимости (только если сервис требует доступа к прототипам)
tonic = { version = "0.5.2", optional = true }
prost = { version = "0.8.0", optional = true }
testcontainers = { version = "0.12.0", optional = true }
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres", "migrate", "ipnetwork", "chrono"], optional = true }


[build-dependencies]
tonic-build = "0.5.2"

# view localy (requires nightly rust toolchain):
# RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --open
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]