#
# Конфигурация комнаты для запуска unity тестов
#
id: 1
auto_create_user: true
# список ожидаемых пользователей
users:
  - public_key: 1
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 2
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 3
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 4
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 5
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 6
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 7
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 8
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 9
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 10
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 11
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 12
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 13
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 14
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 15
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 16
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 17
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 18
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - public_key: 19
    private_key: [ 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15

#permissions:
#  - templates:
#      - template: 10
#        groups:
#         - group: 0b111
#           mode: ro | rw | deny
#        fields:
#          - field_id: 100
#            groups:
#              - group: 0b111
#                mode: ro | rw | deny