apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: cheetahdockerregistry
      containers:
        - name: {{ .Chart.Name }}
          image: "registry.dev.cheetah.games/cheetah/platform/{{ .Chart.Name }}:{{ .Values.global.platformImageVersion }}"
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: "0.25"
              memory: 20Mi
            requests:
              cpu: "0.25"
              memory: 10Mi
          env:
            - name: "JWT_PUBLIC_KEY"
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: public