replicaCount: 1
redis:
  master:
    persistence:
      size: 50Mi
  fullnameOverride: cerberus-redis
  existingSecret: cerberus-redis-password
  existingSecretPasswordKey: password
  cluster:
    enabled: false
  volumePermissions:
    enabled: true
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
