replicaCount: 1
imageVersion: 999.999.999
redis:
  master:
    persistence:
      enabled: false
      size: 1Gi
  architecture: standalone
  fullnameOverride: cheetah-auth-cerberus-redis
  auth:
    existingSecret: cheetah-auth-cerberus-redis-password
    existingSecretPasswordKey: password
  cluster:
    enabled: false
  volumePermissions:
    enabled: true
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001