apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: cheetahdockerregistry
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.registry.cheetah.games/{{ .Chart.Name }}:{{ .Values.global.platformImageVersion }}"
          imagePullPolicy: Always
          env:
            - name: "REDIS_HOST"
              value: "$(CHEETAH_REGISTRY_REDIS_MASTER_SERVICE_HOST)"
            - name: "REDIS_PORT"
              value: "$(CHEETAH_REGISTRY_REDIS_MASTER_SERVICE_PORT)"
            - name: "REDIS_AUTH"
              valueFrom:
                secretKeyRef:
                  name: cheetah-registry-redis-password
                  key: password
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOKI_URL
              value: {{.Values.global.lokiUrl}}

