apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace}}
---
# роль для аллоцирования игровых серверов
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allocate-game-server
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace}}
    name: {{ .Chart.Name }}
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: agones-allocator
  apiGroup: rbac.authorization.k8s.io
---
# роль для получения ip адреса игрового сервера
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace}}
    name: {{ .Chart.Name }}
    apiGroup: ""
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
