#
# Конфигурация комнаты для запуска unity тестов
#
id: 3
auto_create_user: false
# список ожидаемых пользователей
users:
  - id: 1
    private_key: [ 3,1,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - id: 2
    private_key: [ 3,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15