[package]
name = "cheetah-matches-factory"
version = "999.999.999"
edition = "2018"

[[bin]]
name = "service"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.7", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
log = "0.4"
pretty_env_logger = "0.4.0"
tonic = "0.4.2"
prost = "0.7"
cheetah-microservice = { path = "../../../Microservice/" }
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_yaml = "0.8.17"
rmp-serde = "0.15.5"
rmpv = { version = "0.4.7", features = ["with-serde"] }
tokio-stream = { version = "0.1.7", features = ["net"] }


[dev-dependencies]
tempfile = "3.2.0"

[build-dependencies]
tonic-build = "0.4.2"
