replicaCount: 1
imageVersion: 999.999.999
redis:
  master:
    persistence:
      size: 1Gi
  fullnameOverride: cheetah-auth-cerberus-redis
  existingSecret: cheetah-auth-cerberus-redis-password
  existingSecretPasswordKey: password
  cluster:
    enabled: false
  volumePermissions:
    enabled: true
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001