apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: test.dev.cheetah.games
      http:
        paths:
          - path: /games.cheetah.{{ .Chart.Name }}.*
            pathType: Prefix
            backend:
              service:
                name: "{{ .Chart.Name }}-external"
                port:
                  number: 5000