  {{ $secret := (lookup "v1" "Secret" .Release.Namespace "cerberus-redis-password") }}
apiVersion: v1
kind: Secret
metadata:
  name: cerberus-redis-password
type: Opaque
  {{ if $secret}}
data:
  password: {{ $secret.data.password }}
  {{ else }}
stringData:
  password: {{ uuidv4 | quote }}
  {{ end }}