[workspace]
members = [
    "Microservice",
    "auth/*/",
    "matches/Factory",
    "matches/StubMatchmaking",
    "matches/StubRegistry",
    "matches/Relay/Macro",
    "matches/Relay/Common",
    "matches/Relay/Client",
    "matches/Relay/Server"]