[workspace]
members = [
    "Microservice",
    "auth/*/",
    "matches/*",
    "matches/Relay/Macro",
    "matches/Relay/Common",
    "matches/Relay/Client",
    "matches/Relay/Server"]
exclude = ["matches/Relay/.", "matches/Registry"]