# docker compose
#
# - используется только для создания образов для всех сервисов платформы
# - нельзя использовать для запуска, вместо этого используется запуск из Unity
#
# сборка:
#  docker compose -f build-compose.yaml build
#
version: "3.1"
services:
  cerberus:
    image: docker.registry.cheetah.games/cheetah-auth-cerberus:${PLATFORM_VERSION}
    build:
      context: ../
      dockerfile: server/auth/Cerberus/Dockerfile
  authentication:
    image: docker.registry.cheetah.games/cheetah-auth-authentication:${PLATFORM_VERSION}
    build:
      context: ../
      dockerfile: server/auth/Authentication/Dockerfile
  cheetah-match-relay:
    image: docker.registry.cheetah.games/cheetah-matches-relay:${PLATFORM_VERSION}
    build:
      context: ../
      dockerfile: server/matches/Relay/Dockerfile
  cheetah-match-factory:
    image: docker.registry.cheetah.games/cheetah-matches-factory:${PLATFORM_VERSION}
    build:
      context: ../
      dockerfile: server/matches/Factory/Dockerfile
  cheetah-match-stub-making:
    image: docker.registry.cheetah.games/cheetah-match-stub-matchmaking:${PLATFORM_VERSION}
    build:
      context: ../
      dockerfile: server/matches/StubMatchmaking/Dockerfile
  cheetah-match-stub-registry:
    image: docker.registry.cheetah.games/cheetah-matches-stub-registry:${PLATFORM_VERSION}
    build:
      context: ../
      dockerfile: server/matches/StubRegistry/Dockerfile