# docker compose
#
# - используется только для создания образов для всех сервисов платформы
# - нельзя использовать для запуска, вместо этого используется запуск из Unity
#
# сборка:
#  docker compose -f build-compose.yaml build
#
version: "3.1"
services:
#  cheetah-accounts:
#    image: registry.dev.cheetah.games/cheetah/platform/cheetah-accounts:${PLATFORM_VERSION}
#    build:
#      context: ../
#      dockerfile: server/Accounts/Dockerfile
  cheetah-matches-relay:
    image: registry.dev.cheetah.games/cheetah/platform/cheetah-matches-relay:${PLATFORM_VERSION}
    build:
      context: ../
      dockerfile: server/matches/Relay/Dockerfile
#  cheetah-matches-factory:
#    image: registry.dev.cheetah.games/cheetah/platform/cheetah-matches-factory:${PLATFORM_VERSION}
#    build:
#      context: ../
#      dockerfile: server/matches/Factory/Dockerfile
#  cheetah-matches-stub-making:
#    image: registry.dev.cheetah.games/cheetah/platform/cheetah-matches-stub-matchmaking:${PLATFORM_VERSION}
#    build:
#      context: ../
#      dockerfile: server/matches/StubMatchmaking/Dockerfile
#  cheetah-matches-stub-registry:
#    image: registry.dev.cheetah.games/cheetah/platform/cheetah-matches-stub-registry:${PLATFORM_VERSION}
#    build:
#      context: ../
#      dockerfile: server/matches/StubRegistry/Dockerfile
#  cheetah-matches-registry:
#    image: registry.dev.cheetah.games/cheetah/platform/cheetah-matches-registry:${PLATFORM_VERSION}
#    build:
#      context: ../
#      dockerfile: server/matches/Registry/Dockerfile
