[package]
name = "cheetah-matches-stub-registry"
version = "999.999.999"
edition = "2018"

[[bin]]
name = "cheetah-matches-stub-registry"
path = "src/bin/service.rs"

[dependencies]
tokio = { version = "1.16.1", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
log = "0.4"
pretty_env_logger = "0.4.0"
tonic = "0.6.2"
prost = "0.9.0"
cheetah-microservice = { path = "../../Microservice" }

[build-dependencies]
tonic-build = "0.6.2"
