[package]
name = "cheetah-matches-relay-client"
version = "0.0.1"
authors = ["kviring <alex@kviring.com>"]
edition = "2018"

[lib]
name = "cheetah_matches_relay_client"
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
lazy_static = "1.4.0"
log = "0.4"
cheetah-matches-relay-common = { path = "../Common" }
widestring = "0.5.1"
fnv = "1.0.7"
heapless = { version = "0.7.7", features = ["serde"] }


[dev-dependencies]
cheetah-matches-relay = { path = "../Server" }
log = "0.4"
stderrlog = "0.5"
easybench = "1.0.0"
rand = "0.8.3"
env_logger = "0.9.0"