apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  annotations:
    configmap.reloader.stakater.com/reload: "{{ .Values.global.roomTemplates}}"
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: cheetahdockerregistry
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.registry.cheetah.games/{{ .Chart.Name }}:{{ .Values.global.platformImageVersion }}"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.25"
              memory: 40Mi
            requests:
              cpu: "0.25"
              memory: 20Mi
          env:
            - name: TEMPLATES_PATH
              value: /tmp/config/
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOKI_URL
              value: {{.Values.global.lokiUrl}}
          volumeMounts:
            - mountPath: /var/lib/room-templates/
              readOnly: true
              name: room-templates
          command:
            - 'sh'
            - '-c'
            - 'mkdir -p /tmp/config && tar -xzf /var/lib/room-templates/configs.tgz -C /tmp/config && /service'
      volumes:
        - name: room-templates
          configMap:
            name: "rooms-configuration"