apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  imagePullSecrets:
    - name: cheetahdockerregistry
  containers:
    - name: {{ .Chart.Name }}
      image: "docker.registry.cheetah.games/{{ .Chart.Name }}:{{ .Values.imageVersion }}"
      imagePullPolicy: Always
      ports:
        - name: game
          containerPort: 5555
          protocol: UDP
