apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: documentation
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - docs.cheetah.games
      secretName: documentation
  rules:
    - host: docs.cheetah.games
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: "documentation"
                port:
                  number: 8080