[package]
name = "template"
version = "999.999.999"
edition = "2018"

[[bin]]
name = "template"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.7", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
log = "0.4"
pretty_env_logger = "0.4.0"
tonic = "0.4.3"
prost = "0.7"


[build-dependencies]
tonic-build = "0.4.2"
