[package]
name = "cheetah_relay_client"
version = "0.0.1"
authors = ["kviring <alex@kviring.com>"]
edition = "2018"

[lib]
name = "cheetah_relay_client"
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
lazy_static = "1.4.0"
log = "0.4"
cheetah_relay_common = { path = "../../Common" }
widestring = "0.4.2"
hex = "0.4.2"
fnv = "1.0.7"
heapless = { version = "0.5.6", features = ["serde"] }


[dev-dependencies]
cheetah_relay = { path = "../../Server" }
log = "0.4"
stderrlog = "0.5"
easybench = "1.0.0"
rand = "0.8.0"
env_logger = "0.8.2"