apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  template:
    spec:
      ports:
        - name: default
          containerPort: 5555
      template:
        spec:
          imagePullSecrets:
            - name: cheetahdockerregistry
          containers:
            - name: relay
              image: "docker.registry.cheetah.games/cheetah-matches-relay:{{ .Values.global.platformImageVersion }}"
              imagePullPolicy: Always
              env:
                - name: ENABLE_AGONES
                  value: "true"
                # используется для публикации адреса relay в registry
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: CHEETAH_MATCHES_REGISTRY_INTERNAL_SERVICE_HOST
                  value: "$(CHEETAH_MATCHES_REGISTRY_INTERNAL_SERVICE_HOST)"
                - name: CHEETAH_MATCHES_REGISTRY_INTERNAL_SERVICE_PORT
                  value: "$(CHEETAH_MATCHES_REGISTRY_INTERNAL_SERVICE_PORT)"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: LOKI_URL
                  value: {{.Values.global.lokiUrl}}


