#
# Конфигурация комнаты для запуска unity тестов
#
id: 15
auto_create_user: false
# список ожидаемых пользователей
users:
  - id: 1
    private_key: [ 15,1,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - id: 2
    private_key: [ 15,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15