#
# Конфигурация комнаты для запуска unity тестов
#
id: 7
auto_create_user: false
# список ожидаемых пользователей
users:
  - id: 1
    private_key: [ 7,1,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15
  - id: 2
    private_key: [ 7,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 ]
    access_groups: 15