version: "3.1"
services:
  auth_postgres:
    image: postgres:13.1-alpine
    container_name: auth_postgres
    ports:
      - "${AUTH_POSTGRES_HOST}:${AUTH_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
  cerberus_redis:
    image: redis:6.2.1
    container_name: cerberus_redis
    ports:
      - "${CERBERUS_REDIS_HOST}:${CERBERUS_REDIS_PORT}:6379"