[package]
name = "games-cheetah-cerberus-service"
version = "999.999.999"
edition = "2018"


[dependencies]
base64 = "0.13.0"
chrono = "0.4"
tonic = "0.4.0"
prost = "0.7"
tokio = { version = "1.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tokio-stream = { version = "0.1", features = ["net"] }
async-stream = "0.3"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
tower = { version = "0.4" }
jsonwebtoken = "7.2.0"
serde = { version = "1.0", features = ["derive"] }
games-cheetah-cerberus-library = { path = "../Library" }

[build-dependencies]
tonic-build = "0.4.0"