[package]
name = "cheetah-matches-registry"
version = "999.999.999"
edition = "2018"

[[bin]]
name = "cheetah-matches-registry"
path = "src/bin/main.rs"

[dependencies]
pin-project = "1.0.10"
pin-project-internal = "1.0.10"
tokio = { version = "1.16.1", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tonic = "0.6.2"
prost = "0.9.0"
cheetah-microservice = { path = "../../Microservice" }
thiserror = "1.0"
redis = { version = "0.21.4", features = ["tokio-comp"] }
futures = "0.3.19"
async-trait = "0.1.52"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.79"
tracing = "0.1.31"

[dev-dependencies]
testcontainers = "0.12.0"
lazy_static = "1.4.0"

[build-dependencies]
tonic-build = "0.6.2"
