[package]
name = "cheetah-matches-registry"
version = "999.999.999"
edition = "2018"

[[bin]]
name = "cheetah-matches-registry"
path = "src/bin/service.rs"

[dependencies]
tokio = { version = "1.10.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
log = "0.4"
pretty_env_logger = "0.4.0"
tonic = "0.5.2"
prost = "0.8.0"
kube = { version = "0.63.2", default-features = false, features = ["runtime", "derive", "rustls-tls", "client"] }
kube-derive = { version = "0.63.2", default-features = false }
k8s-openapi = { version = "0.13.1", default-features = false, features = ["v1_22"] }
cheetah-microservice = { path = "../../Microservice" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_yaml = "0.8.21"
schemars = "0.8.6"
validator = { version = "0.14.0", features = ["derive"] }
thiserror = "1.0"

[build-dependencies]
tonic-build = "0.5.2"
