apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: cheetahdockerregistry
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.registry.cheetah.games/{{ .Chart.Name }}:{{ .Chart.AppVersion}}"
          imagePullPolicy: Always
          env:
            - name: COOKIE
              value: "true"
            - name: "JWT_PUBLIC_KEY"
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: public
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-postgresql"
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-postgresql"
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-postgresql"
                  key: password