apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "relay-"
spec:
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 5555
  template:
    spec:
      containers:
        - name: relay
          image: docker.registry.cheetah.games/cheetah-matches-relay:999.999.999
          env:
            - name: ENABLE_AGONES
              value: "true"
