name: Release docker images
on:
  release:
    types: [ published ]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - directory: auth/Cerberus
            image: cheetah-auth-cerberus
          - directory: auth/User
            image: cheetah-auth-user
          - directory: auth/Cookie
            image: cheetah-auth-cookie
          - directory: auth/Google
            image: cheetah-auth-google
          - directory: matches/Relay
            image: cheetah-matches-relay
          - directory: matches/StubMatchmaking
            image: cheetah-matches-stub-matchmaking
          - directory: matches/StubRegistry
            image: cheetah-matches-stub-registry
          - directory: matches/Factory
            image: cheetah-matches-factory
          - directory: matches/Registry
            image: cheetah-matches-registry
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: |
            /tmp/.buildx-cache
          key: ${{ matrix.image }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ matrix.image }}-buildx-
      - name: Setup buildkit
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to docker.registry.cheetah.games
        uses: docker/login-action@v1
        with:
          registry: docker.registry.cheetah.games
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          file: server/${{ matrix.directory }}/Dockerfile
          tags: docker.registry.cheetah.games/${{ matrix.image }}:${{ github.event.release.tag_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move buildkit cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache