name: Release unity packages
on:
  release:
    types: [ published ]
jobs:
  release-unity-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - games.cheetah.auth.authentication
          - games.cheetah.auth.cerberus
          - games.cheetah.auth.cookie
          - games.cheetah.auth.google
          - games.cheetah.matches.factory
          - games.cheetah.matches.matchmaking
          - games.cheetah.matches.registry
          - games.cheetah.matches.relay.shared
          - games.cheetah.platfrom
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.registry.cheetah.games'
      - run: cd clients/Unity/Packages/ && sed -i.bak 's/999.999.999/${{ github.event.release.tag_name }}/' ${{ matrix.package}}/package.json
      - run: cd clients/Unity/Packages/ && npm publish ${{ matrix.package}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_REPOSITORY_CHEETAH_GAMES}}