name: Release relay client libraries

on:
  release:
    types: [ published ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            server/target
          key: cargo-macos-${{ hashFiles('**/Cargo.lock') }}
      - name: Build client
        run: cd server && cargo build --manifest-path matches/Relay/Client/Cargo.toml --release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: |
            server/target/release/libcheetah_matches_relay_client.dylib
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            server/target
          key: cargo-linux-${{ hashFiles('**/Cargo.lock') }}
      - name: Build client
        run: cd server/ && cargo build --manifest-path matches/Relay/Client/Cargo.toml --release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: |
            server/target/release/libcheetah_matches_relay_client.so
  build-android-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            server/relay/target
          key: cargo-android-windows-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cross
        run: cargo install --version 0.1.16 cross
      - name: Build windows (client & server)
        run: cd server/ && cross build --manifest-path matches/Relay/Client/Cargo.toml --target x86_64-pc-windows-gnu --release
      - name: Build android armv7-linux-androideabi
        run: cd server/ && cross build --manifest-path matches/Relay/Client/Cargo.toml --target armv7-linux-androideabi --release
      - name: Build android aarch64-linux-android
        run: cd server/ && cross build --manifest-path matches/Relay/Client/Cargo.toml --target aarch64-linux-android --release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-windows-build
          path: |
            server/target/x86_64-pc-windows-gnu/release/cheetah_matches_relay_client.dll
            server/target/armv7-linux-androideabi/release/libcheetah_matches_relay_client.so
            server/target/aarch64-linux-android/release/libcheetah_matches_relay_client.so
  publish-unity-package:
    runs-on: ubuntu-latest
    needs: [ build-mac, build-linux, build-android-windows ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: macos-build
          path: macos-build
      - uses: actions/download-artifact@v2
        with:
          name: linux-build
          path: linux-build
      - uses: actions/download-artifact@v2
        with:
          name: android-windows-build
          path: android-windows-build
      - run: cp macos-build/libcheetah_matches_relay_client.dylib clients/Unity/Packages/games.cheetah.matches.relay/x86_64/libcheetah_matches_relay_client.bundle
      - run: cp linux-build/libcheetah_matches_relay_client.so clients/Unity/Packages/games.cheetah.matches.relay/x86_64/libcheetah_matches_relay_client.so
      - run: cp android-windows-build/x86_64-pc-windows-gnu/release/cheetah_matches_relay_client.dll clients/Unity/Packages/games.cheetah.matches.relay/x86_64/cheetah_matches_relay_client.dll
      - run: cp android-windows-build/armv7-linux-androideabi/release/libcheetah_matches_relay_client.so clients/Unity/Packages/games.cheetah.matches.relay/Android/armv7/libcheetah_matches_relay_client.so
      - run: cp android-windows-build/aarch64-linux-android/release/libcheetah_matches_relay_client.so clients/Unity/Packages/games.cheetah.matches.relay/Android/aarch64/libcheetah_matches_relay_client.so
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '12.x'
          registry-url: 'https://npm.registry.cheetah.games'
      - run: sed -i.bak 's/999.999.999/${{ github.event.release.tag_name }}/' clients/Unity/Packages/games.cheetah.matches.relay/package.json
      - run: npm publish clients/Unity/Packages/games.cheetah.matches.relay/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_REPOSITORY_CHEETAH_GAMES}}
