name: Release helm charts.
on:
  release:
    types: [ published ]
jobs:
  release-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: |
          helm version
          find . -name Chart.yaml | xargs -I {} sed -i.bak 's/999.999.999/${{ github.event.release.tag_name }}/' {}
          find . -name values.yaml | xargs -I {} sed -i.bak 's/999.999.999/${{ github.event.release.tag_name }}/' {}
          cd hosting/charts/Platform
          helm dependency update .
          export HELM_EXPERIMENTAL_OCI=1
          helm registry login docker.registry.cheetah.games -u ${{ secrets.DOCKER_REGISTRY_USER }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          helm package .
          helm push platform-${{ github.event.release.tag_name }}.tgz oci://docker.registry.cheetah.games

