#
# Unit тесты серверных компонентов
#
name: Server tests
on:
  push:
    branches:
      - zakharovvi
      - kviring
jobs:
  server-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            server/target
          key: rust-test-${{ github.sha }}
          restore-keys: |
            rust-test-
      - run: rustup override set 1.56.0
      - run: rustup component add rustfmt --toolchain 1.56.0-x86_64-unknown-linux-gnu
      - name: Run rust test
        run: cd server/ && cargo test


