name: Test
on: [ push ]
jobs:
  relay-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            components/relay/target
          key: cargo-relay
      - name: Test
        run: cargo test --manifest-path components/relay/Cargo.toml
  components:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ cerberus, auth ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            components/${{ matrix.component }}/server/target
          key: cargo-${{ matrix.component }}
      - name: Test
        run: cargo test --manifest-path components/${{ matrix.component }}/server/Cargo.toml
  docker-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - cerberus
          - auth
    steps:
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.component }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.component }}
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          context: components
          push: false
          file: components/${{ matrix.component }}/Dockerfile
          tags: user/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move buildkit cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache