#
# Unit тесты серверных компонентов
#
name: Server tests
on:
  push:
    branches:
      - lain-dono
      - kviring
      - dependabot
jobs:
  server-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            server/target
          key: server-unit-test-${{ github.sha }}
          restore-keys: |
            server-unit-test-
      - run: |
          cd server
          cargo test
