name: Rust
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - name: test server
      run: cd Server && cargo test --verbose
    - name: test rust client
      run: cd clients/Rust && cargo test --verbose

