name: Test
on: [push]
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            components/relay/target
          key: cargo-linux-${{ hashFiles('**/Cargo.lock') }}
      - name: Test Relay
        run: cargo test --manifest-path components/relay/Cargo.toml
      - name: Test Cerberus
        run: cargo test --manifest-path components/cerberus/server/Cargo.toml
