name: Test
on: [push]
jobs:
  relay-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            components/relay/target
          key: cargo-relay
      - name: Test
        run: cargo test --manifest-path components/relay/Cargo.toml
  components:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ cerberus, auth ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            components/${{ matrix.component }}/server/target
          key: cargo-${{ matrix.component }}
      - name: Test
        run: cargo test --manifest-path components/${{ matrix.component }}/server/Cargo.toml
