#
# Интеграционный тест
#
# 1. Собираем docker image для всех компонентов кластера
# 2. Запускаем сервер в kubernetes на digital ocean и запускаем e2e тесты из Unity
# 3. Запускам локальный сервер на docker и запускаем e2e тесты из Unity
#
name: Integration test
on:
  push:
    branches:
      - zakharovvi
      - kviring
      - dependabot
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - directory: auth/Cerberus
            image: cheetah-auth-cerberus
          - directory: auth/User
            image: cheetah-auth-user
          - directory: auth/Cookie
            image: cheetah-auth-cookie
          - directory: auth/Google
            image: cheetah-auth-google
          - directory: matches/Relay
            image: cheetah-matches-relay
          - directory: matches/StubMatchmaking
            image: cheetah-matches-stub-matchmaking
          - directory: matches/StubRegistry
            image: cheetah-matches-stub-registry
          - directory: matches/Factory
            image: cheetah-matches-factory
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ matrix.image }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ matrix.image }}-buildx-
      - name: Setup buildkit
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to docker.registry.cheetah.games
        uses: docker/login-action@v1
        with:
          registry: docker.registry.cheetah.games
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          file: server/${{ matrix.directory }}/Dockerfile
          tags: docker.registry.cheetah.games/${{ matrix.image }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move buildkit cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  build-relay-client-so:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            server/target/
            /tmp/cross-target
          key: build-relay-client-so-${{ github.sha }}
          restore-keys: |
            build-relay-client-so-
      - name: Install cross
        run: cargo install --version 0.1.16 cross --target-dir=/tmp/cross-target
      - name: Compile relay client
        run: |
          cd server
          cross build --manifest-path matches/Relay/Client/Cargo.toml --release --target x86_64-unknown-linux-gnu
          cp target/x86_64-unknown-linux-gnu/release/libcheetah_matches_relay_client.so /tmp/libcheetah_matches_relay_client.so
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: relay-client-so
          path: |
            /tmp/libcheetah_matches_relay_client.so
  integration-kuberenetes-test:
    runs-on: ubuntu-latest
    needs:
      - build-docker-images
      - build-relay-client-so
    # так как получение SSL сертификата для домена операция не быстрая
    # то тестирование для разных pull request осуществляется на одном домене
    # поэтому одновременный запуск данного action не возможен
    concurrency: ${{ github.ref }}
    # иногда что-то в хостинге может пойти не по-плану
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: |
            clients/Unity/Library
          key: integration-kuberenetes-test-${{ github.sha }}
          restore-keys: |
            integration-kuberenetes-test-
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
          sleep 10
      - name: Set branch name
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Prepare namespace
        run: |
          helm uninstall ${{ steps.vars.outputs.short_ref }} -n ${{ steps.vars.outputs.short_ref }} || true
          kubectl delete --namespace ${{ steps.vars.outputs.short_ref }} --all deployments,statefulsets,services,pods,pvc,pv
      - name: Deploy Release
        run: |
          cd hosting/charts/
          tar -czf Platform/charts/matches-factory/rooms-configuration.tgz -C ../../server/matches/Factory/example/ .
          find . -name Platform/values.yaml | xargs -I {} sed -i.bak 's/999.999.999/${{ github.sha }}/' {}
          helm upgrade --debug --install ${{ steps.vars.outputs.short_ref }} \
            --namespace=${{ steps.vars.outputs.short_ref }} \
            Platform \
            -f Platform/values-dev.yaml \
            --set global.grpcDomain=${{ steps.vars.outputs.short_ref }}.cluster.dev.cheetah.games \
            --wait=true
          sleep 10
      - uses: actions/download-artifact@v2
        with:
          name: relay-client-so
          path: clients/Unity/Packages/games.cheetah.matches.relay/x86_64/
      - name: Configure clients/Unity/integration-test-config.json
        run: echo '{"ServerHost":"${{ steps.vars.outputs.short_ref }}.cluster.dev.cheetah.games"}' > clients/Unity/integration-test-config.json
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: clients/Unity/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: PlayMode
          useNetworkHost: true
      - name: Cleanup namespace
        # удалять namespace нельзя, так как там есть сертификаты let encrypt
        # поэтому удаляем релиз и все не нужные ресурсы
        run: |
          helm uninstall ${{ steps.vars.outputs.short_ref }} -n ${{ steps.vars.outputs.short_ref }}
          kubectl delete --namespace ${{ steps.vars.outputs.short_ref }} --all deployments,statefulsets,services,pods,pvc,pv
  integration-docker-test:
    runs-on: ubuntu-latest
    needs:
      - build-docker-images
      - build-relay-client-so
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: |
            clients/Unity/Library
          key: integration-docker-test-${{ github.sha }}
          restore-keys: |
            integration-docker-test-    
      - name: Login to docker.registry.cheetah.games
        uses: docker/login-action@v1
        with:
          registry: docker.registry.cheetah.games
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - uses: actions/download-artifact@v2
        with:
          name: relay-client-so
          path: clients/Unity/Packages/games.cheetah.matches.relay/x86_64/
      - name: Configure integration-test-config.json
        run: echo '{"ServerImageVersion":"${{ github.sha }}"}' > clients/Unity/integration-test-config.json
      - name: Configure cheetah-docker-registry.json
        run: echo '{"Login":"${{ secrets.DOCKER_REGISTRY_USER }}","Password":"${{ secrets.DOCKER_REGISTRY_PASSWORD}}"}' >clients/Unity/cheetah-docker-registry.json
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: clients/Unity/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: PlayMode
          useHostNetwork: true
