name: Test
on: [push]
jobs:
  relay-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            components/relay/target
          key: cargo-relay-${{ hashFiles('**/Cargo.lock') }}
      - name: test
        run: cargo test --manifest-path components/relay/Cargo.toml
  cerberus-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            components/cerberus/server/target
          key: cargo-cerberus-${{ hashFiles('**/Cargo.lock') }}
      - name: test
        run: cargo test --manifest-path components/cerberus/server/Cargo.toml
