#
# Unit тесты серверных компонентов
#
name: Server tests
on:
  push:
    branches:
      - zakharovvi
      - kviring
jobs:
  server-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: rust-server-test-${{ github.sha }}
          restore-keys: |
            rust-server-test-
      - run: rustup override set 1.58.1
      - run: rustup component add rustfmt
      - name: Run rust test
        run: cd server/ && cargo test


