#
# Unit тесты серверных компонентов
#
name: Server tests
on:
  push: 
jobs:
  server-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            server/target
          key: rust-test-${{ github.sha }}
          restore-keys: |
            rust-test-
      - name: Install minimal nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, llvm-tools-preview
      - name: Test
        run: cd server/ && cargo test


