name: Test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ cerberus, authentication, relay ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            server/${{ matrix.component }}/target
            /tmp/.buildx-cache
          key: cargo-${{ matrix.component }}
      - name: Rust test
        run: cargo test --manifest-path server/${{ matrix.component }}/Cargo.toml
      - name: Setup buildkit
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build docker image
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          push: false
          file: server/${{ matrix.component }}/Dockerfile
          tags: user/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move buildkit cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  check-meta-files-in-relay-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - clients/Unity/Packages/games.cheetah.relay/Android/armv7/libcheetah_relay_client.so.meta
          - clients/Unity/Packages/games.cheetah.relay/Android/aarch64/libcheetah_relay_client.so.meta
          - clients/Unity/Packages/games.cheetah.relay/x86_64/libcheetah_relay_client.bundle.meta
          - clients/Unity/Packages/games.cheetah.relay/x86_64/libcheetah_relay_client.dll.meta
          - clients/Unity/Packages/games.cheetah.relay/x86_64/libcheetah_relay_client.so.meta
    steps:
      - uses: actions/checkout@v2
      - run: test -f "${{ matrix.file}}" || exit -1