#
# В режиме разработчика данные не сохраняются на диск
#
cheetah-accounts:
  redis:
    master:
      tolerations:
        - key: "production"
          value: "syncario"
          operator: "Equal"
          effect: "NoSchedule"
      persistence:
        enabled: false
  persistence:
    enabled: false
cheetah-matches-registry:
  redis:
    master:
      tolerations:
        - key: "production"
          value: "syncario"
          operator: "Equal"
          effect: "NoSchedule"
reloader:
  reloader:
    deployment:
      tolerations:
        - key: "production"
          value: "syncario"
          operator: "Equal"
          effect: "NoSchedule"
global:
  lokiUrl: http://monitoring-loki.monitoring:3100
  tolerations:
    key: "production"
    value: "syncario"