#
# В режиме разработчика данные не сохраняются на диск
#
cheetah-accounts:
  redis:
    master:
      persistence:
        enabled: false
ydb:
  storage: memory
reloader:
  reloader:
    deployment:
global:
  lokiUrl: http://monitoring-loki.monitoring:3100
  tolerations:
    key: "stage"
    value: "all"